%% MATLAB to Python Compilation Script
% Compiles rf_emulator.m to a Python package

% Configuration
PACKAGE_NAME = 'rf_channel_pkg';
MATLAB_VERSION = 'R2025b';
OUTPUT_DIR = './matlab_compiled';

% Clean previous builds
if exist(OUTPUT_DIR, 'dir')
    rmdir(OUTPUT_DIR, 's');
end

fprintf('========================================\n');
fprintf('MATLAB to Python Compilation\n');
fprintf('========================================\n');
fprintf('Package name: %s\n', PACKAGE_NAME);
fprintf('MATLAB version: %s\n', MATLAB_VERSION);
fprintf('Output directory: %s\n', OUTPUT_DIR);
fprintf('========================================\n\n');

%% Compile to Python package
fprintf('Step 1: Compiling MATLAB code...\n');

try
    % The -W python flag generates a Python package
    % -T link:lib creates a library
    % -d specifies output directory
    % -v enables verbose output
    
    mcc('-W', ['python:' PACKAGE_NAME], ...
        '-T', 'link:lib', ...
        '-d', OUTPUT_DIR, ...
        '-v', ...
        'rf_emulator.m', ...
        'init_channel.m');
    
    fprintf('\n✓ Compilation successful!\n');
    
catch ME
    fprintf('\n✗ Compilation failed: %s\n', ME.message);
    rethrow(ME);
end

%% Verify output
fprintf('\nStep 2: Verifying output...\n');

if exist(fullfile(OUTPUT_DIR, 'setup.py'), 'file')
    fprintf('✓ setup.py found\n');
else
    error('✗ setup.py not found - compilation may have failed');
end

if exist(fullfile(OUTPUT_DIR, PACKAGE_NAME), 'dir')
    fprintf('✓ Package directory found: %s/\n', PACKAGE_NAME);
else
    error('✗ Package directory not found');
end

%% Display next steps
fprintf('\n========================================\n');
fprintf('Compilation Complete!\n');
fprintf('========================================\n');
fprintf('Next steps:\n');
fprintf('1. Install the package:\n');
fprintf('   cd %s\n', OUTPUT_DIR);
fprintf('   pip install .\n\n');
fprintf('2. Test in Python:\n');
fprintf('   python -c "import %s; print(''Success!'')"\n\n', PACKAGE_NAME);
fprintf('3. Build Docker container with MATLAB Runtime\n');
fprintf('========================================\n');

%% Create README for the compiled package
readme_content = sprintf(['# %s - Compiled MATLAB Package\n\n', ...
    'This package was compiled from MATLAB using MATLAB Compiler SDK.\n\n', ...
    '## Installation\n\n', ...
    '```bash\n', ...
    'pip install .\n', ...
    '```\n\n', ...
    '## Requirements\n\n', ...
    '- Python 3.8, 3.9, 3.10, or 3.11\n', ...
    '- MATLAB Runtime %s (automatically downloaded if not present)\n\n', ...
    '## Usage\n\n', ...
    '```python\n', ...
    'import %s\n\n', ...
    '# Initialize the package\n', ...
    'pkg = %s.initialize()\n\n', ...
    '# Initialize channel\n', ...
    'config = {\n', ...
    '    ''snr_db'': 20,\n', ...
    '    ''doppler_shift'': 10,\n', ...
    '    ''channel_model'': ''Rayleigh''\n', ...
    '}\n', ...
    'pkg.init_channel(config)\n\n', ...
    '# Process data\n', ...
    'tx_data = [1, 2, 3, 4, 5]\n', ...
    'rx_data, metrics = pkg.rf_emulator(tx_data, nargout=2)\n\n', ...
    '# Cleanup\n', ...
    'pkg.terminate()\n', ...
    '```\n\n', ...
    '## File Size Warning\n\n', ...
    'This compiled package is small (~10 MB), but requires MATLAB Runtime\n', ...
    '(~3 GB) to execute. The Runtime will be downloaded automatically\n', ...
    'on first use if not already installed.\n'], ...
    PACKAGE_NAME, MATLAB_VERSION, PACKAGE_NAME, PACKAGE_NAME);

readme_path = fullfile(OUTPUT_DIR, 'README.md');
fid = fopen(readme_path, 'w');
fprintf(fid, '%s', readme_content);
fclose(fid);

fprintf('Created README.md in output directory\n');