transmitter:
  sample_rate: 1000000    # 1 MHz
  carrier_freq: 10000     # Lower frequency for stability
  symbol_rate: 10000      # 10 ksymbols/s (more samples per symbol)

receiver:
  sample_rate: 1000000
  carrier_freq: 10000
  symbol_rate: 10000

channel:
  snr_db: 30              # High SNR for debugging
  noise_factor: 0.01

network:
  host: '0.0.0.0'
  udp_port: 5000
  tcp_port: 5001